#!/bin/bash
# MySQL Connection Helper for DStreamBolt

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🗄️  DStreamBolt MySQL Connection Info"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📍 Host: 13.232.132.240 (DevOps Node)"
echo "👤 User: dstreambolt"
echo "🔑 Password: DStreamBolt2025!"
echo "💾 Database: dstreambolt_metrics"
echo ""
echo "⚠️  Note: Root user requires sudo (auth_socket)"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📝 Connection Commands:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1️⃣  Connect with dstreambolt user (RECOMMENDED):"
echo "   ssh -i ~/dstreambolt-access-key.pem ubuntu@13.232.132.240"
echo "   mysql -u dstreambolt -p'DStreamBolt2025!' dstreambolt_metrics"
echo ""
echo "2️⃣  Connect as root (requires sudo):"
echo "   ssh -i ~/dstreambolt-access-key.pem ubuntu@13.232.132.240"
echo "   sudo mysql"
echo ""
echo "3️⃣  Connect remotely (if port 3306 is open):"
echo "   mysql -h 13.232.132.240 -u dstreambolt -p'DStreamBolt2025!' dstreambolt_metrics"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📊 Quick Queries:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Check Spark results:"
echo "  mysql -u dstreambolt -p'DStreamBolt2025!' -e 'SELECT COUNT(*) FROM dstreambolt_metrics.spark_results;'"
echo ""
echo "Check ingestion metrics:"
echo "  mysql -u dstreambolt -p'DStreamBolt2025!' -e 'SELECT * FROM dstreambolt_metrics.ingestion_metrics ORDER BY timestamp DESC LIMIT 10;'"
echo ""
echo "Check bundle status:"
echo "  mysql -u dstreambolt -p'DStreamBolt2025!' -e 'SELECT * FROM dstreambolt_metrics.bundle_status ORDER BY updated_at DESC LIMIT 10;'"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🔍 Database Tables:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📊 spark_results - Processed Spark data"
echo "📈 ingestion_metrics - Ingestion API metrics"
echo "📦 bundle_status - Bundle processing status"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🔧 First Time Setup:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "If 'dstreambolt' user doesn't exist, run:"
echo "  ssh -i ~/dstreambolt-access-key.pem ubuntu@13.232.132.240"
echo "  bash fix_mysql_auth.sh"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

