#!/bin/bash

###############################################################################
# DStreamBolt One-Click Deployment
# Complete infrastructure setup with zero manual intervention
###############################################################################

set -e

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "$SCRIPT_DIR"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo "╔══════════════════════════════════════════════════════════════╗"
echo "║     🚀 DStreamBolt One-Click Deployment                     ║"
echo "║        Complete Infrastructure Automation                   ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""

# Check if DNS should be configured
USE_DNS=false
if [ "$1" = "--with-dns" ] || [ "$1" = "-d" ]; then
    USE_DNS=true
    echo "✅ DNS configuration will be included"
else
    echo "ℹ️  Skipping DNS configuration (use --with-dns to enable)"
fi
echo ""

# Check prerequisites
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📋 Checking Prerequisites"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

# Check Terraform
if ! command -v terraform &> /dev/null; then
    echo "❌ Terraform not found. Please install Terraform first."
    exit 1
fi
echo "✅ Terraform: $(terraform version -json | python3 -c 'import sys, json; print(json.load(sys.stdin)["terraform_version"])' 2>/dev/null || terraform version | head -1)"

# Check AWS CLI
if ! command -v aws &> /dev/null; then
    echo "❌ AWS CLI not found. Please install AWS CLI first."
    exit 1
fi
echo "✅ AWS CLI: $(aws --version | cut -d' ' -f1)"

# Check AWS credentials
if ! aws sts get-caller-identity &> /dev/null; then
    echo "❌ AWS credentials not configured. Run 'aws configure' first."
    exit 1
fi
AWS_ACCOUNT=$(aws sts get-caller-identity --query Account --output text)
AWS_REGION=$(aws configure get region || echo "ap-south-1")
echo "✅ AWS Account: $AWS_ACCOUNT"
echo "✅ AWS Region: $AWS_REGION"
echo ""

# Check if terraform.tfvars exists
if [ ! -f "terraform.tfvars" ]; then
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo "⚠️  Creating terraform.tfvars"
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

    # Generate secure random password
    MYSQL_PASSWORD=$(openssl rand -base64 32 | tr -d "=+/" | cut -c1-25)

    cat > terraform.tfvars << EOF
# DStreamBolt Infrastructure Configuration
# Auto-generated by deploy.sh

project_name         = "dstreambolt"
aws_region          = "$AWS_REGION"
key_name            = "dstreambolt-access-key"
mysql_root_password = "$MYSQL_PASSWORD"

# Optional DNS configuration
use_custom_domain   = $USE_DNS
domain_name         = "dstreambolt.click"
EOF

    echo "✅ Created terraform.tfvars with secure password"
    echo ""
fi

# Check SSH key
KEY_NAME=$(grep key_name terraform.tfvars | cut -d'=' -f2 | tr -d ' "')
if [ ! -f "$HOME/${KEY_NAME}.pem" ]; then
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo "🔑 Creating SSH Key Pair"
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

    # Check if key exists in AWS
    if aws ec2 describe-key-pairs --key-names "$KEY_NAME" --region "$AWS_REGION" &> /dev/null; then
        echo "⚠️  Key pair exists in AWS but not locally"
        echo "   Deleting and recreating..."
        aws ec2 delete-key-pair --key-name "$KEY_NAME" --region "$AWS_REGION"
    fi

    # Create new key pair
    aws ec2 create-key-pair \
        --key-name "$KEY_NAME" \
        --region "$AWS_REGION" \
        --query 'KeyMaterial' \
        --output text > "$HOME/${KEY_NAME}.pem"

    chmod 600 "$HOME/${KEY_NAME}.pem"
    echo "✅ Created SSH key: $HOME/${KEY_NAME}.pem"
    echo ""
fi

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🏗️  Terraform Deployment"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# Initialize Terraform
echo "1️⃣  Initializing Terraform..."
terraform init -upgrade

# Validate configuration
echo ""
echo "2️⃣  Validating configuration..."
terraform validate

# Plan
echo ""
echo "3️⃣  Planning infrastructure..."
terraform plan -out=tfplan

# Apply
echo ""
echo "4️⃣  Applying infrastructure..."
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
read -p "Continue with deployment? (yes/no): " -r
if [[ ! $REPLY =~ ^[Yy][Ee][Ss]$ ]]; then
    echo "Deployment cancelled."
    exit 0
fi

terraform apply tfplan

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "⏳ Waiting for instances to be ready..."
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "This may take 5-10 minutes for user_data scripts to complete..."
echo ""

# Get outputs
ALB_DNS=$(terraform output -raw alb_dns_name 2>/dev/null || echo "")
DEVOPS_IP=$(terraform output -json direct_access 2>/dev/null | python3 -c "import sys, json; print(json.load(sys.stdin).get('devops_ip', ''))" 2>/dev/null || echo "")
KAFKA_IP=$(terraform output -json direct_access 2>/dev/null | python3 -c "import sys, json; print(json.load(sys.stdin).get('kafka_ip', ''))" 2>/dev/null || echo "")
SPARK_MASTER_IP=$(terraform output -json direct_access 2>/dev/null | python3 -c "import sys, json; print(json.load(sys.stdin).get('compute_ip', ''))" 2>/dev/null || echo "")

# Wait for user_data to complete
echo "Monitoring instance readiness..."
sleep 30

for i in {1..20}; do
    echo -n "."
    sleep 15
done
echo ""
echo "✅ Initial wait complete (5 minutes)"
echo ""

# DNS Configuration (if enabled)
if [ "$USE_DNS" = true ]; then
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo "🌐 DNS Configuration"
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo ""

    # Run SSL setup script
    if [ -f "../scripts/setup_domain_ssl.sh" ]; then
        bash ../scripts/setup_domain_ssl.sh
    else
        echo "⚠️  DNS setup script not found. SSL certificate must be configured manually."
        echo "   Follow instructions in SSL_CERTIFICATE_SETUP.md"
    fi
fi

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🔍 Verifying Deployment"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# Test ALB
if [ ! -z "$ALB_DNS" ]; then
    echo "Testing ALB endpoint..."
    HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" -k "https://$ALB_DNS/" --connect-timeout 10 || echo "000")
    if [ "$HTTP_CODE" -ge 200 ] && [ "$HTTP_CODE" -lt 400 ]; then
        echo "✅ ALB is responding (HTTP $HTTP_CODE)"
    else
        echo "⚠️  ALB returned HTTP $HTTP_CODE (services may still be starting)"
    fi
fi

# Test SSH access to DevOps
if [ ! -z "$DEVOPS_IP" ]; then
    echo ""
    echo "Testing SSH access to DevOps node..."
    if ssh -i "$HOME/${KEY_NAME}.pem" -o StrictHostKeyChecking=no -o ConnectTimeout=10 ubuntu@$DEVOPS_IP "echo 'SSH OK'" &> /dev/null; then
        echo "✅ SSH access to DevOps node working"
    else
        echo "⚠️  SSH access to DevOps node not ready yet"
    fi
fi

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✅ Deployment Complete!"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# Show access information
echo "╔══════════════════════════════════════════════════════════════╗"
echo "║                  📋 Access Information                       ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""

if [ "$USE_DNS" = true ]; then
    echo "🌐 Primary Access (with DNS):"
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo "  Landing Page:  https://dstreambolt.click/"
    echo "  Jenkins:       https://jenkins.dstreambolt.click/"
    echo "  Grafana:       https://grafana.dstreambolt.click/"
    echo "  Kafka Manager: https://kafkamgr.dstreambolt.click/"
    echo "  Spark UI:      https://spark.dstreambolt.click/"
    echo "  Ingestion:     https://ingest.dstreambolt.click/"
    echo ""
fi

echo "🔗 ALB Access (always works):"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  Landing Page:  https://$ALB_DNS/"
echo "  Jenkins:       https://$ALB_DNS/jenkins"
echo "  Grafana:       https://$ALB_DNS/grafana"
echo "  Kafka Manager: https://$ALB_DNS/kafkamgr"
echo "  Spark UI:      https://$ALB_DNS/spark"
echo "  Ingestion:     https://$ALB_DNS/ingest"
echo ""

echo "🖥️  Direct Instance Access:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  DevOps:       ssh -i ~/${KEY_NAME}.pem ubuntu@$DEVOPS_IP"
echo "  Kafka:        ssh -i ~/${KEY_NAME}.pem ubuntu@$KAFKA_IP (via DevOps)"
echo "  Spark Master: ssh -i ~/${KEY_NAME}.pem ubuntu@$SPARK_MASTER_IP"
echo ""

echo "🔐 Credentials:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
terraform output -json credentials 2>/dev/null || echo "  Run: terraform output credentials"
echo ""

echo "📊 Full Configuration:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  View all outputs: terraform output"
echo "  SSH key location: $HOME/${KEY_NAME}.pem"
echo "  MySQL password:   terraform output -raw mysql_root_password"
echo ""

if [ "$USE_DNS" = false ]; then
    echo "ℹ️  To enable DNS access:"
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo "  1. Run: ./deploy.sh --with-dns"
    echo "  2. Or run: ../scripts/setup_domain_ssl.sh"
    echo "  3. Add DNS CNAME record as instructed"
    echo ""
fi

echo "╔══════════════════════════════════════════════════════════════╗"
echo "║          🎉 DStreamBolt is Ready to Use!                    ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""

# Save deployment info
cat > deployment_info.txt << EOF
DStreamBolt Deployment Information
===================================
Deployed: $(date)
AWS Account: $AWS_ACCOUNT
AWS Region: $AWS_REGION

Access URLs:
- ALB: https://$ALB_DNS/
- DevOps: ssh -i ~/${KEY_NAME}.pem ubuntu@$DEVOPS_IP

Run 'terraform output' for full details.
EOF

echo "📝 Deployment info saved to: deployment_info.txt"
echo ""

